global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: lakehouse_aqe_metrics
    scrape_interval: 30s
    static_configs:
      - targets: ["metrics-exporter:9101"]

  # Opsional: Spark JMX exporter
  # - job_name: spark
  #   static_configs:
  #     - targets: ["spark-master:4040"]
